class GramNidanFieldDef {
  final String id;
  final String label;
  final String type; // e.g., 'text', 'yesno', 'upt', 'growth', etc.

  const GramNidanFieldDef(this.id, this.label, {this.type = 'text'});
}

class GramNidanModuleDef {
  final String id;
  final String title;
  final String icon;
  final List<GramNidanFieldDef> fields;

  const GramNidanModuleDef({
    required this.id,
    required this.title,
    required this.icon,
    required this.fields,
  });
}

class GramNidanModuleDefinitions {
  static const List<GramNidanModuleDef> modules = [
    GramNidanModuleDef(
      id: 'village',
      title: 'Village Survey / Master Household',
      icon: '🏘️',
      fields: [
        GramNidanFieldDef('houseno', 'Parivar Sankhya (House No / Family ID)', type: 'text'),
        GramNidanFieldDef('mukhia', 'Mukhia Ka Naam (Head of Family)', type: 'text'),
        GramNidanFieldDef('members', 'Sadasyon Ka Naam, Aayu, Ling', type: 'text'),
        GramNidanFieldDef('mobile', 'Mobile Number', type: 'text'),
        GramNidanFieldDef('toilet', 'Shauchalay Hai Ya Nahi', type: 'text'),
        GramNidanFieldDef('category', 'Category (SC/ST/OBC/General)', type: 'text'),
        GramNidanFieldDef('pmjay', 'PMJAY Card', type: 'yesno'),
        GramNidanFieldDef('palliative', 'Palliative Care (Long-term Bedridden/Terminal Patient)', type: 'yesno'),
        GramNidanFieldDef('abha', 'ABHA ID / Aadhaar Number (Prati Sadasya)', type: 'text'),
        GramNidanFieldDef('rationcard', 'Ration Card Category (Yellow-BPL / Orange / White)', type: 'text'),
        GramNidanFieldDef('watersource', 'Peene Ke Paani Ka Srot (Tap Water / Well / Handpump)', type: 'text'),
        GramNidanFieldDef('housetype', 'Ghar Ka Prakar (Pucca / Kutcha)', type: 'text'),
        GramNidanFieldDef('ancflag', 'Pregnant Woman Ghar Mein Hai? (ANC Flag)', type: 'yesno'),
        GramNidanFieldDef('pncflag', 'Lactating Mother / Infant 1 Yr Hai? (PNC Flag)', type: 'yesno'),
        GramNidanFieldDef('childrencount', 'Bachhe 0-5 Yrs (Sankhya + SAM/MAM Status)', type: 'text'),
        GramNidanFieldDef('eligiblecouple', 'Eligible Couple (15-49 Yrs) Ghar Mein Hai? (Contraceptive Tracking)', type: 'yesno'),
        GramNidanFieldDef('disability', 'Disability / Divyangjan Case Hai?', type: 'yesno'),
        GramNidanFieldDef('migration', 'Seasonal Migration Status (Us-tod / Construction Labor)', type: 'yesno'),
        GramNidanFieldDef('tbcase', 'TB Case Hai?', type: 'yesno'),
        GramNidanFieldDef('leprosycase', 'Leprosy Case Hai?', type: 'yesno'),
        GramNidanFieldDef('othercase', 'Other Disease Case Hai?', type: 'yesno'),
        GramNidanFieldDef('diseasename', 'Disease Ka Naam (agar Other)', type: 'text'),
        GramNidanFieldDef('diseasestatus', 'Kya Hua Unka (Status/Outcome)', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'ec',
      title: 'Eligible Couple Register',
      icon: '👪',
      fields: [
        GramNidanFieldDef('couple', 'Pati aur Patni Ka Naam', type: 'text'),
        GramNidanFieldDef('age', 'Dono Ki Aayu', type: 'text'),
        GramNidanFieldDef('children', 'Jeevit Bachhon Ki Sankhya', type: 'text'),
        GramNidanFieldDef('youngestchildage', 'Age of Youngest Child (Months/Years)', type: 'text'),
        GramNidanFieldDef('method', 'Current Contraceptive Method', type: 'text'),
        GramNidanFieldDef('sterilization', 'Sterilization Plan', type: 'text'),
        GramNidanFieldDef('lmpdate', 'LMP Date (Period Delay Tracking)', type: 'text'),
        GramNidanFieldDef('uptdate', 'Date of Test', type: 'text'),
        GramNidanFieldDef('upt', 'UPT Status (Positive / Negative / Pending)', type: 'upt'),
      ],
    ),
    GramNidanModuleDef(
      id: 'anc',
      title: 'ANC Register',
      icon: '🤰',
      fields: [
        GramNidanFieldDef('name', 'Pregnant Woman Name Husband Name', type: 'text'),
        GramNidanFieldDef('rchid', 'RCH ID / MCTS ID', type: 'text'),
        GramNidanFieldDef('abhaid', 'ABHA ID (14-digit)', type: 'text'),
        GramNidanFieldDef('mobile', 'Mobile Number', type: 'text'),
        GramNidanFieldDef('gravida', 'Gravida / Parity', type: 'text'),
        GramNidanFieldDef('ancvisits', '4 ANC Checkup Dates', type: 'text'),
        GramNidanFieldDef('lmp', 'LMP (Last Menstrual Period)', type: 'text'),
        GramNidanFieldDef('edd', 'EDD (Expected Delivery Date)', type: 'text'),
        GramNidanFieldDef('bpsys', 'BP Systolic', type: 'text'),
        GramNidanFieldDef('bpdia', 'BP Diastolic', type: 'text'),
        GramNidanFieldDef('weightkg', 'Weight (kg) This Visit', type: 'text'),
        GramNidanFieldDef('motherheight', 'Mother\'s Height (cm)', type: 'text'),
        GramNidanFieldDef('calcium', 'Calcium Tablets Given', type: 'yesno'),
        GramNidanFieldDef('hb', 'Hemoglobin (Hb) g/dL', type: 'text'),
        GramNidanFieldDef('urineprotein', 'Urine Protein', type: 'urineprotein4'),
        GramNidanFieldDef('urinesugar', 'Urine Sugar', type: 'nilpresent'),
        GramNidanFieldDef('bloodgroup', 'Blood Group', type: 'bloodgroup4'),
        GramNidanFieldDef('rhflag', 'Rh - ve Alert Flag', type: 'yesno'),
        GramNidanFieldDef('ogtt', 'Blood Sugar / OGTT', type: 'normalhighrisk'),
        GramNidanFieldDef('sicklecell', 'Sickle Cell Screening', type: 'sicklecell3'),
        GramNidanFieldDef('infectionscreen', 'HIV / VDRL (Syphilis) / HBsAg (Hep-B) Panel', type: 'normalhighrisk'),
        GramNidanFieldDef('usgstatus', 'USG / Sonography Scan Status', type: 'donepending'),
        GramNidanFieldDef('labremarks', 'Thyroid (T3/T4/TSH), Sonography (USG), LFT/KFT Other Remarks', type: 'text'),
        GramNidanFieldDef('abdomexam', 'Abdominal Examination', type: 'text'),
        GramNidanFieldDef('tt1', 'TT-1', type: 'yesno'),
        GramNidanFieldDef('tt2', 'TT-2', type: 'yesno'),
        GramNidanFieldDef('ttbooster', 'Booster', type: 'yesno'),
        GramNidanFieldDef('ifagiven', 'IFA (Iron) Given', type: 'yesno'),
        GramNidanFieldDef('ifadose', 'IFA Dosage/Strength', type: 'text'),
        GramNidanFieldDef('tabletcount', 'Tablet Count (Remaining)', type: 'text'),
        GramNidanFieldDef('albendazole', 'Albendazole Given', type: 'yesno'),
        GramNidanFieldDef('hrphighbp', 'High BP', type: 'yesno'),
        GramNidanFieldDef('hrpanemia', 'Severe Anemia', type: 'yesno'),
        GramNidanFieldDef('hrphb', 'Hb 7', type: 'yesno'),
        GramNidanFieldDef('hrprh', 'Rh - ve Blood', type: 'yesno'),
        GramNidanFieldDef('hrpdiabetes', 'Diabetes', type: 'yesno'),
        GramNidanFieldDef('hrptwins', 'Twins / Breech Presentation', type: 'yesno'),
        GramNidanFieldDef('hrp', 'Overall High-Risk Pregnancy Status', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'delivery',
      title: 'Delivery & PNC',
      icon: '🍼',
      fields: [
        GramNidanFieldDef('mothername', 'Mother Ka Naam / RCH ID', type: 'text'),
        GramNidanFieldDef('datetime', 'Delivery Date Time', type: 'text'),
        GramNidanFieldDef('place', 'Place of Delivery', type: 'text'),
        GramNidanFieldDef('deliverytype', 'Type of Delivery (Normal / C-Section / Assisted)', type: 'text'),
        GramNidanFieldDef('conductedby', 'Delivery Conducted By (ANM / Doctor / Dai / Self)', type: 'text'),
        GramNidanFieldDef('outcome', 'Outcome (Jeevit shishu / Stillbirth)', type: 'text'),
        GramNidanFieldDef('newborngender', 'Newborn Gender', type: 'gender3'),
        GramNidanFieldDef('babyweight', 'Baby Birth Weight', type: 'text'),
        GramNidanFieldDef('pncday1', 'PNC Visit Day 1', type: 'yesno'),
        GramNidanFieldDef('pncday3', 'PNC Visit Day 3', type: 'yesno'),
        GramNidanFieldDef('pncday7', 'PNC Visit Day 7', type: 'yesno'),
        GramNidanFieldDef('pncday14', 'PNC Visit Day 14', type: 'yesno'),
        GramNidanFieldDef('pncday21', 'PNC Visit Day 21', type: 'yesno'),
        GramNidanFieldDef('pncday28', 'PNC Visit Day 28', type: 'yesno'),
        GramNidanFieldDef('pncday42', 'PNC Visit Day 42', type: 'yesno'),
        GramNidanFieldDef('motherhealth', 'Mother\'s Health Status', type: 'text'),
        GramNidanFieldDef('pph', 'PPH (Postpartum Hemorrhage) Flag', type: 'yesno'),
        GramNidanFieldDef('eclampsia', 'Eclampsia Flag', type: 'yesno'),
        GramNidanFieldDef('referralinst', 'Referral Institution (if any)', type: 'text'),
        GramNidanFieldDef('jsy', 'JSY / JSSK Cash Benefit Status', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'hbnc',
      title: 'HBNC Register',
      icon: '🏠',
      fields: [
        GramNidanFieldDef('namewt', 'Shishu Ka Naam / Birth Weight', type: 'text'),
        GramNidanFieldDef('sex', 'Newborn Gender', type: 'text'),
        GramNidanFieldDef('mothername', 'Mother Ka Naam', type: 'text'),
        GramNidanFieldDef('bcgbirth', 'BCG (Birth Dose)', type: 'yesno'),
        GramNidanFieldDef('opv0', 'OPV-0 (Birth Dose)', type: 'yesno'),
        GramNidanFieldDef('hepbbirth', 'Hep-B (Birth Dose)', type: 'yesno'),
        GramNidanFieldDef('hbncday1', 'HBNC Visit Day 1', type: 'yesno'),
        GramNidanFieldDef('hbncday3', 'HBNC Visit Day 3', type: 'yesno'),
        GramNidanFieldDef('hbncday7', 'HBNC Visit Day 7', type: 'yesno'),
        GramNidanFieldDef('hbncday14', 'HBNC Visit Day 14', type: 'yesno'),
        GramNidanFieldDef('hbncday21', 'HBNC Visit Day 21', type: 'yesno'),
        GramNidanFieldDef('hbncday28', 'HBNC Visit Day 28', type: 'yesno'),
        GramNidanFieldDef('hbncday42', 'HBNC Visit Day 42', type: 'yesno'),
        GramNidanFieldDef('temp', 'Temperature Record', type: 'text'),
        GramNidanFieldDef('cord', 'Umbilical Cord Condition', type: 'text'),
        GramNidanFieldDef('jaundice', 'Jaundice / Skin Color', type: 'text'),
        GramNidanFieldDef('bf', 'Exclusive Breastfeeding Status', type: 'text'),
        GramNidanFieldDef('danger', 'Danger Signs', type: 'text'),
        GramNidanFieldDef('urine', 'Urine', type: 'text'),
        GramNidanFieldDef('stool', 'Stool', type: 'text'),
        GramNidanFieldDef('congenital', 'Congenital Anomaly (Birth Defect)', type: 'text'),
        GramNidanFieldDef('sncu', 'SNCU Referral Status', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'hbyc',
      title: 'HBYC Register',
      icon: '🧒',
      fields: [
        GramNidanFieldDef('nameage', 'Child Name Age', type: 'text'),
        GramNidanFieldDef('visitmonth', 'Visit Months (3,6,9,12,15)', type: 'text'),
        GramNidanFieldDef('feeding', 'Complementary Feeding Start Date', type: 'text'),
        GramNidanFieldDef('ifa', 'IFA Syrup Bottle Distribution', type: 'text'),
        GramNidanFieldDef('muac', 'MUAC Tape Reading', type: 'text'),
        GramNidanFieldDef('milestones', 'Developmental Milestones', type: 'text'),
        GramNidanFieldDef('wt3', 'Weight Height 3 Month Visit', type: 'text'),
        GramNidanFieldDef('wt6', 'Weight Height 6 Month Visit', type: 'text'),
        GramNidanFieldDef('wt9', 'Weight Height 9 Month Visit', type: 'text'),
        GramNidanFieldDef('wt12', 'Weight Height 12 Month Visit', type: 'text'),
        GramNidanFieldDef('wt15', 'Weight Height 15 Month Visit', type: 'text'),
        GramNidanFieldDef('deworming', 'Deworming Syrup Status', type: 'yesno'),
        GramNidanFieldDef('orszinc', 'ORS / Zinc Distribution Log', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'child',
      title: 'Immunization / UIP',
      icon: '💉',
      fields: [
        GramNidanFieldDef('nameinfo', 'Child Name, DOB, Gender', type: 'text'),
        GramNidanFieldDef('bcg', 'BCG', type: 'yesno'),
        GramNidanFieldDef('hepbzero', 'Hepatitis B Zero Dose', type: 'yesno'),
        GramNidanFieldDef('opvzero', 'Oral Polio Zero Dose (OPV-0)', type: 'yesno'),
        GramNidanFieldDef('penta1', 'Pentavalent - I', type: 'yesno'),
        GramNidanFieldDef('fipv1', 'FIPV - I', type: 'yesno'),
        GramNidanFieldDef('rvv1', 'RVV - I', type: 'yesno'),
        GramNidanFieldDef('pcv1', 'PCV - I', type: 'yesno'),
        GramNidanFieldDef('opv1', 'OPV - I', type: 'yesno'),
        GramNidanFieldDef('penta2', 'Pentavalent - II', type: 'yesno'),
        GramNidanFieldDef('opv2', 'OPV - II', type: 'yesno'),
        GramNidanFieldDef('rvv2', 'RVV - II', type: 'yesno'),
        GramNidanFieldDef('penta3', 'Pentavalent - III', type: 'yesno'),
        GramNidanFieldDef('opv3', 'OPV - III', type: 'yesno'),
        GramNidanFieldDef('fipv2', 'FIPV - II', type: 'yesno'),
        GramNidanFieldDef('rvv3', 'RVV - III', type: 'yesno'),
        GramNidanFieldDef('pcv2', 'PCV - II', type: 'yesno'),
        GramNidanFieldDef('mr1', 'MR - I ()', type: 'yesno'),
        GramNidanFieldDef('je1', 'JE - I', type: 'yesno'),
        GramNidanFieldDef('pcvbooster', 'PCV - B (Booster)', type: 'yesno'),
        GramNidanFieldDef('ipv3', 'IPV - III', type: 'yesno'),
        GramNidanFieldDef('dptbooster1', 'DPT Booster - I', type: 'yesno'),
        GramNidanFieldDef('mr2', 'MR - II ()', type: 'yesno'),
        GramNidanFieldDef('je2', 'JE - II', type: 'yesno'),
        GramNidanFieldDef('opvbooster1', 'OPV Booster - I', type: 'yesno'),
        GramNidanFieldDef('dptbooster2', 'DPT Booster - II', type: 'yesno'),
        GramNidanFieldDef('td10', 'TD (10 Years)', type: 'yesno'),
        GramNidanFieldDef('td16', 'TD (16 Years)', type: 'yesno'),
        GramNidanFieldDef('weightchart', 'Monthly Weight Growth Chart Color', type: 'text'),
        GramNidanFieldDef('growthbadge', 'Growth Category Badge', type: 'growth'),
      ],
    ),
    GramNidanModuleDef(
      id: 'cbac',
      title: 'CBAC (NCD Screening)',
      icon: '🩺',
      fields: [
        GramNidanFieldDef('nameage', 'Person Name Age (30+)', type: 'text'),
        GramNidanFieldDef('gender', 'Gender', type: 'text'),
        GramNidanFieldDef('abhaid', 'ABHA ID (14-digit)', type: 'text'),
        GramNidanFieldDef('mobile', 'Mobile Number', type: 'text'),
        GramNidanFieldDef('habits', 'Tobacco / Alcohol Use', type: 'text'),
        GramNidanFieldDef('waist', 'Waist Circumference', type: 'text'),
        GramNidanFieldDef('familyhistory', 'Family History (Diabetes/BP/Cancer)', type: 'text'),
        GramNidanFieldDef('activity', 'Physical Activity (150 min/week)', type: 'text'),
        GramNidanFieldDef('score', 'NCD Risk Score (0-10)', type: 'text'),
        GramNidanFieldDef('cough', 'Chronic Cough (2 Wks) / Voice Change', type: 'yesno'),
        GramNidanFieldDef('oralulcer', 'Oral Ulcer / Sore (2 Wks)', type: 'yesno'),
        GramNidanFieldDef('breastlump', 'Breast Lump / Abnormal Bleeding (Female Only)', type: 'yesno'),
        GramNidanFieldDef('footnumb', 'Foot Numbness / Non-healing Wound', type: 'yesno'),
        GramNidanFieldDef('fueltype', 'Cooking Fuel Type', type: 'text'),
        GramNidanFieldDef('dustexposure', 'Occupational Dust/Smoke Exposure', type: 'yesno'),
      ],
    ),
    GramNidanModuleDef(
      id: 'ncd',
      title: 'NCD Tracking Register',
      icon: '❤️',
      fields: [
        GramNidanFieldDef('nameage', 'Patient Name Age', type: 'text'),
        GramNidanFieldDef('gender', 'Gender', type: 'text'),
        GramNidanFieldDef('abhaid', 'ABHA ID (14-digit)', type: 'text'),
        GramNidanFieldDef('diagnosis', 'Diagnosis (BP / Diabetes / Cancer / Other)', type: 'text'),
        GramNidanFieldDef('diagnoseddate', 'Diagnosed Date', type: 'text'),
        GramNidanFieldDef('medication', 'Current Medication', type: 'text'),
        GramNidanFieldDef('compliance', 'Medication Compliance (Daily / Irregular)', type: 'text'),
        GramNidanFieldDef('cbacfilled', 'CBAC Form Filled (Y/N)', type: 'yesno'),
        GramNidanFieldDef('cbacscore', 'CBAC Score', type: 'text'),
        GramNidanFieldDef('heightcm', 'Height (cms)', type: 'text'),
        GramNidanFieldDef('weightkg', 'Weight (Kg)', type: 'text'),
        GramNidanFieldDef('bmi', 'BMI (Kg/m2)', type: 'text'),
        GramNidanFieldDef('tbcase', 'Tuberculosis Suspect / Confirmed Case', type: 'yesno'),
        GramNidanFieldDef('randomglucose', 'Random Blood Glucose (Mg/dl)', type: 'text'),
        GramNidanFieldDef('oralcancer', 'Oral Cancer Screening (Y/N)', type: 'yesno'),
        GramNidanFieldDef('cervicalcancer', 'Cervical Cancer Screening (Y/N/NA)', type: 'yesno'),
        GramNidanFieldDef('breastcancer', 'Breast Cancer Screening (Y/N/NA)', type: 'yesno'),
        GramNidanFieldDef('otherscreening', 'Others (Pap Smear, Biopsy, Mammography)', type: 'text'),
        GramNidanFieldDef('suspectdate', 'NCD Suspect Identification Date', type: 'text'),
        GramNidanFieldDef('suspectcondition', 'Suspect Condition (HT / DM / Oral / Cervical / Breast Cancer)', type: 'text'),
        GramNidanFieldDef('npcdcsremarks', 'Remarks (Referral for Confirmation, On Treatment, NPCDCS Treatment Reg, Outcome)', type: 'text'),
        GramNidanFieldDef('hb', 'Hemoglobin (Hb) g/dL', type: 'text'),
        GramNidanFieldDef('bpsys', 'BP Systolic', type: 'text'),
        GramNidanFieldDef('bpdia', 'BP Diastolic', type: 'text'),
        GramNidanFieldDef('lastreading', 'Last BP/Sugar Reading (Summary)', type: 'text'),
        GramNidanFieldDef('followup', 'Next Follow-up Due', type: 'text'),
        GramNidanFieldDef('ccheart', 'Heart Complication Screen', type: 'yesno'),
        GramNidanFieldDef('cckidney', 'Kidney Complication Screen', type: 'yesno'),
        GramNidanFieldDef('cceye', 'Eye / Retinopathy Screen', type: 'yesno'),
        GramNidanFieldDef('ccfoot', 'Foot / Neuropathy Screen', type: 'yesno'),
        GramNidanFieldDef('referral', 'Referral/Follow-up Status', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'birthdeath',
      title: 'Birth & Death Register',
      icon: '📝',
      fields: [
        GramNidanFieldDef('eventtype', 'Event Type (Birth / Death)', type: 'text'),
        GramNidanFieldDef('eventdate', 'Date of Event', type: 'text'),
        GramNidanFieldDef('placeofevent', 'Place of Event (Home / Hospital)', type: 'text'),
        GramNidanFieldDef('personname', 'Deceased/Child Name', type: 'text'),
        GramNidanFieldDef('deceasedagegender', 'Deceased Age & Gender (MDR/CDR Audit)', type: 'text'),
        GramNidanFieldDef('cause', 'Cause of Death', type: 'text'),
        GramNidanFieldDef('deathaudit', 'Maternal/Infant Death Audit Flag', type: 'yesno'),
        GramNidanFieldDef('certstatus', 'Registration Certificate Status', type: 'text'),
        GramNidanFieldDef('crsackid', 'CRS Portal Registration Acknowledgement ID', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'idsp',
      title: 'Communicable Disease (IDSP)',
      icon: '🦟',
      fields: [
        GramNidanFieldDef('diseasetype', 'Disease Type (TB / Leprosy / Dengue / Malaria / COVID)', type: 'text'),
        GramNidanFieldDef('patient', 'Patient Name & Symptoms', type: 'text'),
        GramNidanFieldDef('nikshayid', 'Nikshay ID (TB) / NLEP ID (Leprosy)', type: 'text'),
        GramNidanFieldDef('testdate', 'Blood Slide / Sputum Test Date', type: 'text'),
        GramNidanFieldDef('outcome', 'Test Outcome', type: 'text'),
        GramNidanFieldDef('dotsstart', 'DOTS / Drug Treatment Start Date', type: 'text'),
        GramNidanFieldDef('completion', 'Treatment Completion Status', type: 'text'),
        GramNidanFieldDef('contacttracing', 'Family Contact Tracing Status', type: 'yesno'),
        GramNidanFieldDef('nikshaypmy', 'Nikshay Poshan Yojana — DBT Account Status', type: 'text'),
      ],
    ),
    GramNidanModuleDef(
      id: 'inventory',
      title: 'Medicine Inventory & Incentives',
      icon: '📦',
      fields: [
        GramNidanFieldDef('stockors', 'ORS Packets', type: 'text'),
        GramNidanFieldDef('stockparacetamol', 'Paracetamol Tablets', type: 'text'),
        GramNidanFieldDef('stockifa', 'IFA (Iron-Folic Acid) Tablets', type: 'text'),
        GramNidanFieldDef('stockcondoms', 'Condoms', type: 'text'),
        GramNidanFieldDef('stockpregkit', 'Pregnancy Test Kits (Nischay / UPT)', type: 'text'),
        GramNidanFieldDef('kitexpiry', 'Kit Expiry Date Alert', type: 'text'),
        GramNidanFieldDef('taskcount', 'Monthly Task Completed Count', type: 'text'),
        GramNidanFieldDef('claimanc', 'ANC / Delivery Visits Incentive', type: 'text'),
        GramNidanFieldDef('claimimmun', 'Immunization Session Incentive', type: 'text'),
        GramNidanFieldDef('claimncd', 'NCD / CBAC Screening Incentive', type: 'text'),
        GramNidanFieldDef('claimother', 'Other Task-Based Incentive', type: 'text'),
        GramNidanFieldDef('claimamount', 'Total Incentive Claim Form Amount', type: 'text'),
        GramNidanFieldDef('paymentstatus', 'Payment Status', type: 'text'),
        GramNidanFieldDef('pfmsref', 'PFMS Payment Ref ID', type: 'text'),
      ],
    ),
  ];
}
